# Generated by Django 6.0.7 on 2026-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('US', 'Estados Unidos'), ('BR', 'Brasil')], max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Actors',
            },
        ),
    ]
