# Generated by Django 6.0.6 on 2026-06-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actor',
            new_name='Actors',
        ),
    ]
