# Generated by Django 6.0.6 on 2026-06-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_rename_actor_actors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actors',
            options={'verbose_name_plural': 'Actors'},
        ),
    ]
