# Generated by Django 6.0.6 on 2026-06-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_alter_actors_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
