# Generated by Django 6.0.6 on 2026-06-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_alter_actors_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
